parserOptions:
  phpVersion: 7
rules:
  ClassMethodCamelCase: "error"
  Eqeqeq: "error"
  NoInclude: "error"
  NoShortOpenTag: "error"
  UseNamespace: "error"
  ConstantsUpperCase: "error"
  NoEcho: "error"
  NoIniSet: "error"
  NoInlineHtml: "error"
  OneClass: "error"